name: Update Database

on:
  push:
  schedule:
    - cron: '0 */4 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r modules.txt
    
    - name: Download OmegaDB
      uses: wei/wget@v1
      with:
        args: -O database/OmegaDB.cdb https://duelistsunite.org/omega/OmegaDB.cdb
    
    - name: create json
      run: python database/parse_json.py
    
    - name: Auto commit
      run: |
           git config user.name "sunx2"
           git config user.email "xxsunxxrose@gmail.com"
           git add .
           git commit -m "generated"
           git push